# https://travis-ci.com/skeptycal/autosys

# use language: minimal for work in 'alpha' state
language: minimal
#################################################################################
# language: python
# cache: pip

# branches:
#   only:
#     - master

# # python:
# #   - "3.6"
# #   - "3.7"
# #   - "nightly"

# matrix:
#   fast_finish: true
#   include:
#     - python: 3.7
#       dist: xenial
#     - python: pypy3
#       dist: trusty
#     - python: 3.7
#       services:
#         - docker
#       env: BUILD_SDIST=true
#     # macOS
#     - name: generic
#       language: generic
#       os: osx
#       env: PYVER=py37
#     - name: Python 3.5.5 on macOS
#       os: osx
#       language: objective-c
#       env: PYENV_VERSION=3.5.5
#     - name: Python 3.7 on macOS
#       os: osx
#       language: objective-c
#       env: PYENV_VERSION=3.7

# allow_failures:
#   include:
#     - python: 3.7
#       dist: xenial
#     - python: pypy3
#       dist: trusty
#     - python: 3.7
#       services:
#         - docker
#       env: BUILD_SDIST=true
#     # macOS
#     - name: generic
#       language: generic
#       os: osx
#       env: PYVER=py37
#     - name: Python 3.5.5 on macOS
#       os: osx
#       language: objective-c
#       env: PYENV_VERSION=3.5.5
#     - name: Python 3.7 on macOS
#       os: osx
#       language: objective-c
#       env: PYENV_VERSION=3.7
# addons:
#   apt:
#     packages: [libgnutls-dev]

# # For a list of available versions, run
# #     aws s3 ls s3://travis-python-archives/binaries/ubuntu/16.04/x86_64/

# install:
#   - pip install -r requirements.txt
#   - pip install coveralls

# script:
#   - pytest

# deploy:
#   provider: releases
#   file:
#     - dist/*.whl
#     - dist/*.tar.gz
#   file_glob: true
#   on:
#     repo: skeptycal/autosys
#     tags: true
#   skip_cleanup: true

# after_success:
#   # Upload coverage data to codecov
#   codecov
#   coveralls

# notifications:
#   email: skeptycal@gmail.com
# #################################################################################
