#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import fileinput
import re
import sys


class bcolors:
    HEADER = "\033[95m"
    OKBLUE = "\033[94m"
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    FAIL = "\033[91m"

    ENDC = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"


pattern = re.compile(sys.argv[1])
for line in fileinput.input(sys.argv[2:]):
    pat_search = pattern.search(line)
    print("pat_search: ", pat_search)
    if not pat_search:
        print(
            fileinput.filename(),
            fileinput.filelineno(),
            pattern.sub(bcolors.WARNING + pat_search + bcolors.ENDC),
            end="",
        )
